### ISSUE TITLE
What's your 'net' package?

### ISSUE THREAD

**Issue by Quynh-Nguyen** [scorredoira/anviz-soyal-drivers#1]
Hi,

I'm also researching about connect to Soyal.
But I don't know what's `net` package you using. Can you please share me?

**Comment by scorredoira** [comment]
Hi,

Although the syntax is typescript the code is executed by a virtual machine written in Go, so it is https://golang.org/pkg/net

It's a custom stack but the code works so I hope it helps!

**Comment by Quynh-Nguyen** [comment]
@scorredoira 

Thank you so much.
Can you please give me one more favor about how I can run this source.
